/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class ColaEdge : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ColaEdge(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ColaEdge obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ColaEdge() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_ColaEdge(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public ColaEdge() : this(colaPINVOKE.new_ColaEdge__SWIG_0(), true) {
  }

  public ColaEdge(uint t, uint u) : this(colaPINVOKE.new_ColaEdge__SWIG_1(t, u), true) {
  }

  public ColaEdge(ColaEdge p) : this(colaPINVOKE.new_ColaEdge__SWIG_2(ColaEdge.getCPtr(p)), true) {
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint first {
    set {
      colaPINVOKE.ColaEdge_first_set(swigCPtr, value);
    } 
    get {
      uint ret = colaPINVOKE.ColaEdge_first_get(swigCPtr);
      return ret;
    } 
  }

  public uint second {
    set {
      colaPINVOKE.ColaEdge_second_set(swigCPtr, value);
    } 
    get {
      uint ret = colaPINVOKE.ColaEdge_second_get(swigCPtr);
      return ret;
    } 
  }

}

}
