/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class OrthogonalEdgeConstraint : CompoundConstraint {
  private HandleRef swigCPtr;

  internal OrthogonalEdgeConstraint(IntPtr cPtr, bool cMemoryOwn) : base(colaPINVOKE.OrthogonalEdgeConstraintUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OrthogonalEdgeConstraint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OrthogonalEdgeConstraint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_OrthogonalEdgeConstraint(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public OrthogonalEdgeConstraint(uint l, uint r) : this(colaPINVOKE.new_OrthogonalEdgeConstraint(l, r), true) {
  }

  public uint left {
    set {
      colaPINVOKE.OrthogonalEdgeConstraint_left_set(swigCPtr, value);
    } 
    get {
      uint ret = colaPINVOKE.OrthogonalEdgeConstraint_left_get(swigCPtr);
      return ret;
    } 
  }

  public uint right {
    set {
      colaPINVOKE.OrthogonalEdgeConstraint_right_set(swigCPtr, value);
    } 
    get {
      uint ret = colaPINVOKE.OrthogonalEdgeConstraint_right_get(swigCPtr);
      return ret;
    } 
  }

  public override void generateVariables(SWIGTYPE_p_std__vectorT_vpsc__Variable_p_t vars) {
    colaPINVOKE.OrthogonalEdgeConstraint_generateVariables(swigCPtr, SWIGTYPE_p_std__vectorT_vpsc__Variable_p_t.getCPtr(vars));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void generateSeparationConstraints(SWIGTYPE_p_std__vectorT_vpsc__Variable_p_t vs, SWIGTYPE_p_std__vectorT_vpsc__Constraint_p_t cs) {
    colaPINVOKE.OrthogonalEdgeConstraint_generateSeparationConstraints(swigCPtr, SWIGTYPE_p_std__vectorT_vpsc__Variable_p_t.getCPtr(vs), SWIGTYPE_p_std__vectorT_vpsc__Constraint_p_t.getCPtr(cs));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void generateTopologyConstraints(Dim k, RectPtrVector rs, SWIGTYPE_p_std__vectorT_vpsc__Variable_p_t vars, SWIGTYPE_p_std__vectorT_vpsc__Constraint_p_t cs) {
    colaPINVOKE.OrthogonalEdgeConstraint_generateTopologyConstraints(swigCPtr, (int)k, RectPtrVector.getCPtr(rs), SWIGTYPE_p_std__vectorT_vpsc__Variable_p_t.getCPtr(vars), SWIGTYPE_p_std__vectorT_vpsc__Constraint_p_t.getCPtr(cs));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_vpsc__Constraint vpscConstraint {
    set {
      colaPINVOKE.OrthogonalEdgeConstraint_vpscConstraint_set(swigCPtr, SWIGTYPE_p_vpsc__Constraint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = colaPINVOKE.OrthogonalEdgeConstraint_vpscConstraint_get(swigCPtr);
      SWIGTYPE_p_vpsc__Constraint ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_vpsc__Constraint(cPtr, false);
      return ret;
    } 
  }

}

}
