/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class Resize : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Resize(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Resize obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Resize() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_Resize(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public Resize(uint id, double x, double y, double w, double h) : this(colaPINVOKE.new_Resize(id, x, y, w, h), true) {
  }

  public uint getID() {
    uint ret = colaPINVOKE.Resize_getID(swigCPtr);
    return ret;
  }

  public Rectangle getTarget() {
    IntPtr cPtr = colaPINVOKE.Resize_getTarget(swigCPtr);
    Rectangle ret = (cPtr == IntPtr.Zero) ? null : new Rectangle(cPtr, false);
    return ret;
  }

}

}
