#!/usr/bin/python

import os

os.system("ln -s ../../.. pkg")

names = """
destress_aca
orthohub
planarise
leafless
faceset
treeplacement
expand
chainconfig
hola
aca
""".split()

print '...'
for name in names:
    cmd = 'python %s.py' % name
    print '%s complete' % name
    os.system(cmd)

