/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class ConvexCluster : Cluster {
  private HandleRef swigCPtr;

  internal ConvexCluster(IntPtr cPtr, bool cMemoryOwn) : base(colaPINVOKE.ConvexClusterUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ConvexCluster obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ConvexCluster() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_ConvexCluster(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override void computeBoundary(RectPtrVector rs) {
    colaPINVOKE.ConvexCluster_computeBoundary(swigCPtr, RectPtrVector.getCPtr(rs));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__valarrayT_unsigned_int_t hullRIDs {
    set {
      colaPINVOKE.ConvexCluster_hullRIDs_set(swigCPtr, SWIGTYPE_p_std__valarrayT_unsigned_int_t.getCPtr(value));
      if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__valarrayT_unsigned_int_t ret = new SWIGTYPE_p_std__valarrayT_unsigned_int_t(colaPINVOKE.ConvexCluster_hullRIDs_get(swigCPtr), true);
      if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__valarrayT_unsigned_char_t hullCorners {
    set {
      colaPINVOKE.ConvexCluster_hullCorners_set(swigCPtr, SWIGTYPE_p_std__valarrayT_unsigned_char_t.getCPtr(value));
      if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__valarrayT_unsigned_char_t ret = new SWIGTYPE_p_std__valarrayT_unsigned_char_t(colaPINVOKE.ConvexCluster_hullCorners_get(swigCPtr), true);
      if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ConvexCluster() : this(colaPINVOKE.new_ConvexCluster(), true) {
  }

}

}
