/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class Node : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Node(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Node obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Node() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_Node(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public uint id {
    get {
      uint ret = colaPINVOKE.Node_id_get(swigCPtr);
      return ret;
    } 
  }

  public Rectangle rect {
    set {
      colaPINVOKE.Node_rect_set(swigCPtr, Rectangle.getCPtr(value));
    } 
    get {
      IntPtr cPtr = colaPINVOKE.Node_rect_get(swigCPtr);
      Rectangle ret = (cPtr == IntPtr.Zero) ? null : new Rectangle(cPtr, false);
      return ret;
    } 
  }

  public Node(uint id, Rectangle arg1, SWIGTYPE_p_vpsc__Variable arg2) : this(colaPINVOKE.new_Node__SWIG_0(id, Rectangle.getCPtr(arg1), SWIGTYPE_p_vpsc__Variable.getCPtr(arg2)), true) {
  }

  public Node(uint id, Rectangle arg1) : this(colaPINVOKE.new_Node__SWIG_1(id, Rectangle.getCPtr(arg1)), true) {
  }

  public void setDesiredPos(double d, double weight) {
    colaPINVOKE.Node_setDesiredPos__SWIG_0(swigCPtr, d, weight);
  }

  public void setDesiredPos(double d) {
    colaPINVOKE.Node_setDesiredPos__SWIG_1(swigCPtr, d);
  }

  public double initialPos() {
    double ret = colaPINVOKE.Node_initialPos(swigCPtr);
    return ret;
  }

  public double finalPos() {
    double ret = colaPINVOKE.Node_finalPos(swigCPtr);
    return ret;
  }

  public double posOnLine(double alpha) {
    double ret = colaPINVOKE.Node_posOnLine(swigCPtr, alpha);
    return ret;
  }

  public SWIGTYPE_p_vpsc__Variable getVar() {
    IntPtr cPtr = colaPINVOKE.Node_getVar(swigCPtr);
    SWIGTYPE_p_vpsc__Variable ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_vpsc__Variable(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_vpsc__Variable var {
    set {
      colaPINVOKE.Node_var_set(swigCPtr, SWIGTYPE_p_vpsc__Variable.getCPtr(value));
    } 
    get {
      IntPtr cPtr = colaPINVOKE.Node_var_get(swigCPtr);
      SWIGTYPE_p_vpsc__Variable ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_vpsc__Variable(cPtr, false);
      return ret;
    } 
  }

}

}
