/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class OffsetPair : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OffsetPair(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OffsetPair obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OffsetPair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_OffsetPair(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public OffsetPair() : this(colaPINVOKE.new_OffsetPair__SWIG_0(), true) {
  }

  public OffsetPair(uint t, double u) : this(colaPINVOKE.new_OffsetPair__SWIG_1(t, u), true) {
  }

  public OffsetPair(OffsetPair p) : this(colaPINVOKE.new_OffsetPair__SWIG_2(OffsetPair.getCPtr(p)), true) {
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint first {
    set {
      colaPINVOKE.OffsetPair_first_set(swigCPtr, value);
    } 
    get {
      uint ret = colaPINVOKE.OffsetPair_first_get(swigCPtr);
      return ret;
    } 
  }

  public double second {
    set {
      colaPINVOKE.OffsetPair_second_set(swigCPtr, value);
    } 
    get {
      double ret = colaPINVOKE.OffsetPair_second_get(swigCPtr);
      return ret;
    } 
  }

}

}
