/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.adaptagrams.cola {

using System;
using System.Runtime.InteropServices;

public class UnsignedVector : IDisposable, System.Collections.IEnumerable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UnsignedVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UnsignedVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnsignedVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        colaPINVOKE.delete_UnsignedVector(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public UnsignedVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (uint element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public uint this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(System.Array array) {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(System.Array array, int arrayIndex) {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, System.Array array, int arrayIndex, int count) {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  // Type-safe version of IEnumerable.GetEnumerator
  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new UnsignedVectorEnumerator(this);
  }

  public UnsignedVectorEnumerator GetEnumerator() {
    return new UnsignedVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class UnsignedVectorEnumerator : System.Collections.IEnumerator {
    private UnsignedVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public UnsignedVectorEnumerator(UnsignedVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public uint Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (uint)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }
  }

  public void Clear() {
    colaPINVOKE.UnsignedVector_Clear(swigCPtr);
  }

  public void Add(uint x) {
    colaPINVOKE.UnsignedVector_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = colaPINVOKE.UnsignedVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = colaPINVOKE.UnsignedVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    colaPINVOKE.UnsignedVector_reserve(swigCPtr, n);
  }

  public UnsignedVector() : this(colaPINVOKE.new_UnsignedVector__SWIG_0(), true) {
  }

  public UnsignedVector(int capacity) : this(colaPINVOKE.new_UnsignedVector__SWIG_1(capacity), true) {
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint getitemcopy(int index) {
    uint ret = colaPINVOKE.UnsignedVector_getitemcopy(swigCPtr, index);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint getitem(int index) {
    uint ret = colaPINVOKE.UnsignedVector_getitem(swigCPtr, index);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, uint val) {
    colaPINVOKE.UnsignedVector_setitem(swigCPtr, index, val);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(UnsignedVector values) {
    colaPINVOKE.UnsignedVector_AddRange(swigCPtr, UnsignedVector.getCPtr(values));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public UnsignedVector GetRange(int index, int count) {
    IntPtr cPtr = colaPINVOKE.UnsignedVector_GetRange(swigCPtr, index, count);
    UnsignedVector ret = (cPtr == IntPtr.Zero) ? null : new UnsignedVector(cPtr, true);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, uint x) {
    colaPINVOKE.UnsignedVector_Insert(swigCPtr, index, x);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, UnsignedVector values) {
    colaPINVOKE.UnsignedVector_InsertRange(swigCPtr, index, UnsignedVector.getCPtr(values));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    colaPINVOKE.UnsignedVector_RemoveAt(swigCPtr, index);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    colaPINVOKE.UnsignedVector_RemoveRange(swigCPtr, index, count);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public static UnsignedVector Repeat(uint value, int count) {
    IntPtr cPtr = colaPINVOKE.UnsignedVector_Repeat(value, count);
    UnsignedVector ret = (cPtr == IntPtr.Zero) ? null : new UnsignedVector(cPtr, true);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    colaPINVOKE.UnsignedVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    colaPINVOKE.UnsignedVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, UnsignedVector values) {
    colaPINVOKE.UnsignedVector_SetRange(swigCPtr, index, UnsignedVector.getCPtr(values));
    if (colaPINVOKE.SWIGPendingException.Pending) throw colaPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(uint value) {
    bool ret = colaPINVOKE.UnsignedVector_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(uint value) {
    int ret = colaPINVOKE.UnsignedVector_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(uint value) {
    int ret = colaPINVOKE.UnsignedVector_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public void Remove(uint value) {
    colaPINVOKE.UnsignedVector_Remove(swigCPtr, value);
  }

}

}
