Adaptagrams: dialect::OrthoHubLayout Class Reference
dialect::OrthoHubLayout Class Reference
A layout object that tries to orthogonalise hubs. This means it visits nodes of degrees 3 or higher, and tries to set their neighbours in cardinal compass directions from it.
#include <nodeconfig.h>
Public Member Functions
OrthoHubLayout (Graph_SP G, OrthoHubLayoutOptions opts)
Standard constructor.
void layout (Logger *logger=nullptr)
Try to orthogonalise hubs.
Detailed Description
A layout object that tries to orthogonalise hubs. This means it visits nodes of degrees 3 or higher, and tries to set their neighbours in cardinal compass directions from it.
Constructor & Destructor Documentation
OrthoHubLayout()
OrthoHubLayout::OrthoHubLayout (Graph_SP G, OrthoHubLayoutOptions opts)
Standard constructor.
Parameters
[in,out] G the underlying Graph
[in] opts options to control the layout
References dialect::OrthoHubLayoutOptions::avoidFlatTriangles, dialect::OrthoHubLayoutOptions::includeLinks, and dialect::ColaOptions::preventOverlaps.
Member Function Documentation
layout()
void OrthoHubLayout::layout (Logger * logger = nullptr)
Try to orthogonalise hubs.
Parameters
[in] logger Optional logger to record the individual layout steps.
References dialect::ACALayout::applyOAsAllOrNothing(), dialect::OrthoHubLayoutOptions::avoidFlatTriangles, dialect::ColaGraphRep::id2ix, dialect::string_format(), and dialect::ACALayout::updateSepMatrix().
Referenced by dialect::doHOLA().
The documentation for this class was generated from the following files:
libdialect/nodeconfig.h
libdialect/nodeconfig.cpp