Adaptagrams: cola::RectangularCluster Class Reference
cola::RectangularCluster Class Reference
Defines a rectangular cluster, either variable-sized with floating sides or a fixed size based on a particular rectangle.
#include <cluster.h>
Public Member Functions
RectangularCluster ()
A rectangular cluster of variable size that contains its children.
RectangularCluster (unsigned rectIndex)
A fixed size rectangular cluster based on a particular rectangle.
void setMargin (double margin)
Sets the margin size for this cluster.
void setMargin (const cola::Box margin)
Sets the margin box for this cluster.
cola::Box margin (void) const
Returns the margin box for this cluster.
void setPadding (double padding)
Sets the padding size for this cluster.
void setPadding (const cola::Box padding)
Sets the padding box for this cluster.
cola::Box padding (void) const
Returns the padding box for this cluster.
virtual void addChildNode (unsigned index)
Mark a rectangle as being a child of this cluster.
Public Member Functions inherited from cola::Cluster
void addChildCluster (Cluster *cluster)
Mark a cluster as being a sub-cluster of this cluster.
Detailed Description
Defines a rectangular cluster, either variable-sized with floating sides or a fixed size based on a particular rectangle.
The chosen constructor decides the type and behaviour of the cluster.
Constructor & Destructor Documentation
cola::RectangularCluster::RectangularCluster (unsigned rectIndex)
A fixed size rectangular cluster based on a particular rectangle.
This rectangle might be constrained in the other ways like normal rectangles.
Parameters
[in] rectIndex The index of the rectangle that this cluster represents.
References vpsc::XDIM, and vpsc::YDIM.
Member Function Documentation
void cola::RectangularCluster::addChildNode (unsigned index) virtual
Mark a rectangle as being a child of this cluster.
Parameters
[in] index The index of the Rectangle in the rectangles vector.
Reimplemented from cola::Cluster.
References cola::Cluster::addChildNode().
Box cola::RectangularCluster::margin (void) const virtual
Returns the margin box for this cluster.
Returns
The margin box for the cluster.
Reimplemented from cola::Cluster.
Referenced by setMargin().
Box cola::RectangularCluster::padding (void) const virtual
Returns the padding box for this cluster.
Returns
The padding box for the cluster.
Reimplemented from cola::Cluster.
Referenced by setPadding().
void cola::RectangularCluster::setMargin (double margin)
Sets the margin size for this cluster.
This value represents the outer spacing that will be put between the cluster boundary on all sides and other clusters (plus their margin) and rectangles at the same level when non-overlap constraints are enabled.
Parameters
[in] margin The size of the margin for this cluster.
void cola::RectangularCluster::setMargin (const cola::Box margin)
Sets the margin box for this cluster.
This box represents the outer spacing that will be put between the cluster boundary and other clusters (plus their margin) and rectangles at the same level when non-overlap constraints are enabled.
Parameters
[in] margin The box representing the margins for this cluster.
References margin().
void cola::RectangularCluster::setPadding (double padding)
Sets the padding size for this cluster.
This value represents the inner spacing that will be put between the cluster boundary and other child clusters (plus their margin) and child rectangles on all sides.
Parameters
[in] padding The size of the padding for this cluster.
void cola::RectangularCluster::setPadding (const cola::Box padding)
Sets the padding box for this cluster.
This box represents the inner spacing that will be put between the cluster boundary and other child clusters (plus their margin) and child rectangles for each edge.
Parameters
[in] padding The Box representing padding values for this cluster.
References padding().
The documentation for this class was generated from the following files:
libcola/cluster.h
libcola/cluster.cpp