Adaptagrams: cola::ConstrainedFDLayout Class Reference
cola::ConstrainedFDLayout Class Reference
Implements a constrained force-directed layout algorithm.
#include <cola.h>
Public Member Functions
ConstrainedFDLayout (const vpsc::Rectangles &rs, const std::vector< cola::Edge > &es, const double idealLength, const EdgeLengths &eLengths=StandardEdgeLengths, TestConvergence *doneTest=nullptr, PreIteration *preIteration=nullptr)
Constructs a constrained force-directed layout instance.
void run (bool x=true, bool y=true)
Implements the main layout loop, taking descent steps until stress is no-longer significantly reduced.
void runOnce (bool x=true, bool y=true)
Same as run(), but only applies one iteration.
void setConstraints (const cola::CompoundConstraints &ccs)
Specify a set of compound constraints to apply to the layout.
void setAvoidNodeOverlaps (bool avoidOverlaps, ListOfNodeIndexes listOfNodeGroups=ListOfNodeIndexes())
Specifies whether non-overlap constraints should be automatically generated between all nodes, as well as any exemptions to this.
void setTopology (TopologyAddonInterface *topology)
Set an addon for doing topology preserving layout.
void setClusterHierarchy (RootCluster *hierarchy)
Specifies an optional hierarchy for clustering nodes.
void setUnsatisfiableConstraintInfo (UnsatisfiableConstraintInfos *unsatisfiableX, UnsatisfiableConstraintInfos *unsatisfiableY)
Register to receive information about unsatisfiable constraints.
void makeFeasible (void)
Finds a feasible starting position for nodes that satisfies the given constraints.
void freeAssociatedObjects (void)
A convenience method that can be called from Java to free the memory of nodes (Rectangles), CompoundConstraints, etc.
void outputInstanceToSVG (std::string filename=std::string())
Generates an SVG file containing debug output and code that can be used to regenerate the instance.
Detailed Description
Implements a constrained force-directed layout algorithm.
This method is based on a non-linear gradient projection technique. Conceptually it's similar to a force directed method like Fruchterman-Reingold—but using a more principled goal function and optimisation techniques.
Constructor & Destructor Documentation
ConstrainedFDLayout()
cola::ConstrainedFDLayout::ConstrainedFDLayout (const vpsc::Rectangles & rs, const std::vector< cola::Edge > & es, const double idealLength, const EdgeLengths & eLengths = StandardEdgeLengths, TestConvergence * doneTest = nullptr, PreIteration * preIteration = nullptr)
Constructs a constrained force-directed layout instance.
If an empty edges (es) vector is passed to the constructor, then constraint satisfaction will be performed, but no force-directed layout. In this case, idealLength and eLengths have no effect.
Conversely, if no constraints or clusters are specified and no overlap prevention is enabled, but edge info is given, then pure force-directed layout will be performed.
Parameters
[in] rs Bounding boxes of nodes at their initial positions.
[in] es Simple pair edges, giving indices of the start and end nodes in rs.
[in] idealLength A scalar modifier of ideal edge lengths in eLengths or of 1 if no ideal lengths are specified.
[in] eLengths Individual ideal lengths for edges. The actual ideal length used for the ith edge is idealLength*eLengths[i], or if eLengths is nullptr a then just idealLength is used (i.e., eLengths[i] is assumed to be 1).
[in] done A test of convergence operation called at the end of each iteration (optional). If not given, uses a default TestConvergence object.
[in] preIteration An operation called before each iteration (optional).
Member Function Documentation
freeAssociatedObjects()
void cola::ConstrainedFDLayout::freeAssociatedObjects (void)
A convenience method that can be called from Java to free the memory of nodes (Rectangles), CompoundConstraints, etc.
This assumes that the ConstrainedFDLayout instance takes ownership of all the objects passed to it.
This is useful because in SWIG we have problems with Java wrapper classes going out of scope and causing objects like Rectanges to sometimes be freed when the layout instance still needs them. For this reason we prevent the Java wrappers from deleting the internal C++ instances, and let them be cleaned up later via this method.
makeFeasible()
void cola::ConstrainedFDLayout::makeFeasible (void)
Finds a feasible starting position for nodes that satisfies the given constraints.
Starts with an initial position (x, y) for the nodes. This position is then iteratively updated with a greedy heuristic that tries adding additional constraints based on compound constraint priority to the satisfiable set, so as to satisfy as many of the placement constraints as possible. This includes automatically generated constraints for non-overlap and cluster containment.
Note
This method doesn't do force-directed layout. All forces are ignored and it merely satisfies the constraints with minimal movement to nodes.
References vpsc::IncSolver::addConstraint(), cola::generateVariables(), and vpsc::IncSolver::satisfy().
outputInstanceToSVG()
void cola::ConstrainedFDLayout::outputInstanceToSVG (std::string filename = std::string())
Generates an SVG file containing debug output and code that can be used to regenerate the instance.
This method can be called before or after run() or makeFeasible() have been called.
Parameters
[in] filename A string indicating the filename (without extension) for the output file. Defaults to "libcola-debug.svg" if no filename is given.
run()
void cola::ConstrainedFDLayout::run (bool x = true, bool y = true)
Implements the main layout loop, taking descent steps until stress is no-longer significantly reduced.
Parameters
[in] x If true, layout will be performed in x-dimension (default: true).
[in] y If true, layout will be performed in y-dimension (default: true).
runOnce()
void cola::ConstrainedFDLayout::runOnce (bool x = true, bool y = true)
Same as run(), but only applies one iteration.
This may be useful here it's too hard to implement a call-back (e.g., in java apps).
Parameters
[in] x If true, layout will be performed in x-dimension (default: true).
[in] y If true, layout will be performed in y-dimension (default: true).
setAvoidNodeOverlaps()
void cola::ConstrainedFDLayout::setAvoidNodeOverlaps (bool avoidOverlaps, ListOfNodeIndexes listOfNodeGroups = ListOfNodeIndexes())
Specifies whether non-overlap constraints should be automatically generated between all nodes, as well as any exemptions to this.
The optional second parameter indicates groups of nodes that should be exempt from having non-overlap constraints generated between each other. For example, you might want to do this for nodes representing ports, or the child nodes in a particular cluster.
Parameters
[in] avoidOverlaps New boolean value for this option.
[in] listOfNodeGroups A list of groups of node indexes which will not have non-overlap constraints generated between each other.
References vpsc::HORIZONTAL, and vpsc::VERTICAL.
setClusterHierarchy()
void cola::ConstrainedFDLayout::setClusterHierarchy (RootCluster * hierarchy) inline
Specifies an optional hierarchy for clustering nodes.
Parameters
[in] hierarchy A pointer to a RootCluster object defining the the cluster hierarchy (optional).
setConstraints()
void cola::ConstrainedFDLayout::setConstraints (const cola::CompoundConstraints & ccs)
Specify a set of compound constraints to apply to the layout.
Parameters
[in] ccs The compound constraints.
setTopology()
void cola::ConstrainedFDLayout::setTopology (TopologyAddonInterface * topology)
Set an addon for doing topology preserving layout.
It is expected that you would use the topology::ColaTopologyAddon() from libtopology rather than write your own. This is done so that libcola does not have to depend on libtopology.
Parameters
[in] topology Instance of a class implementing the TopologyAddonInterface.
See also
topology::ColaTopologyAddon
References vpsc::HORIZONTAL, vpsc::IncSolver::solve(), and vpsc::VERTICAL.
setUnsatisfiableConstraintInfo()
void cola::ConstrainedFDLayout::setUnsatisfiableConstraintInfo (UnsatisfiableConstraintInfos * unsatisfiableX, UnsatisfiableConstraintInfos * unsatisfiableY) inline
Register to receive information about unsatisfiable constraints.
In the case of unsatisifiable constraints, the solver will drop unsatisfiable constraints of lowest priority. Information about these will be written to these lists after each iteration of constrained layout.
param[out] unsatisfiableX A pointer to a UnsatisfiableConstraintInfos object that will be used to record unsatisfiable constraints in the x-dimension. param[out] unsatisfiableY A pointer to a UnsatisfiableConstraintInfos object that will be used to record unsatisfiable constraints in the y-dimension.
The documentation for this class was generated from the following files:
libcola/cola.h
libcola/colafd.cpp