Adaptagrams: Avoid::ReferencingPolygon Class Reference
Avoid::ReferencingPolygon Class Reference
A Polygon which just references its points from other Polygons.
#include <geomtypes.h>
Public Member Functions
void clear (void)
Resets this to the empty polygon.
bool empty (void) const
Returns true if this polygon is empty.
size_t size (void) const
Returns the number of points in this polygon.
int id (void) const
Returns the ID value associated with this polygon.
const Point & at (size_t index) const
Returns a specific point in the polygon.
Public Member Functions inherited from Avoid::PolygonInterface
PolygonInterface ()
Constructor.
virtual ~PolygonInterface ()
Destructor.
Polygon boundingRectPolygon (void) const
Returns the bounding rectangle for this polygon.
Box offsetBoundingBox (double offset) const
Returns the bounding rectangle that contains this polygon with optionally some buffer space around it for routing.
Detailed Description
A Polygon which just references its points from other Polygons.
This type of Polygon is used to accurately represent cluster boundaries made up from the corner points of shapes.
Member Function Documentation
at()
const Point & Avoid::ReferencingPolygon::at (size_t index) const virtual
Returns a specific point in the polygon.
Parameters
[in] index The array index of the point to be returned.
Implements Avoid::PolygonInterface.
References Avoid::Polygon::ps, Avoid::Polygon::size(), and size().
Referenced by Avoid::Router::outputInstanceToSVG().
The documentation for this class was generated from the following files:
libavoid/geomtypes.h
libavoid/geomtypes.cpp