Adaptagrams: dialect::NodeBuckets Struct Reference
dialect::NodeBuckets Struct Reference
#include <peeling.h>
Public Member Functions
NodeBuckets (Graph &graph)
Initialize a set of node buckets for the given Graph.
NodesById takeLeaves (void)
Return a copy of the bucket of leaves, and clear the latter.
bool moveNode (id_type id, unsigned oldDegree, unsigned newDegree)
Move a node from one bucket to another.
void severNodes (const NodesById &nodes)
Sever the given Nodes from our Graph.
Detailed Description
For sorting all the nodes of a graph into "buckets" according to their degree. You can take all the leaves (degree-1 nodes) and you can move a node from one bucket to another.
Constructor & Destructor Documentation
NodeBuckets()
NodeBuckets::NodeBuckets (Graph & graph)
Initialize a set of node buckets for the given Graph.
Creates buckets for all degrees up to the Graph's max degree, and populates these. Each bucket contains a NodesById map.
References dialect::Graph::getNodeLookup().
Member Function Documentation
moveNode()
bool NodeBuckets::moveNode (id_type id, unsigned oldDegree, unsigned newDegree)
Move a node from one bucket to another.
Parameters
[in] id The ID of the Node to be moved.
[in] oldDegree The bucket in which the Node should be found.
[in] newDegree The bucket to which the Node should be moved.
Returns
boolean saying whether the Node was found and moved.
Referenced by severNodes().
severNodes()
void NodeBuckets::severNodes (const NodesById & nodes)
Sever the given Nodes from our Graph.
Note
This method does modify the Graph. For each given Node, all incident Edges are severed, and the Node is removed from the Graph. The neighbouring Nodes are moved to new buckets as appropriate.
The given Nodes themselves are NOT moved to new buckets. This preserves the freedom to handle that operation separately.
References moveNode(), dialect::Graph::removeNodes(), and dialect::Graph::severNodeNotingNeighbours().
Referenced by dialect::peel().
The documentation for this struct was generated from the following files:
libdialect/peeling.h
libdialect/peeling.cpp